spring:
    application:
        name: ptmatch
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}
    jpa:
        # hibernate:
            # ddl-auto: update
        properties:
            hibernate:
                default_batch_fetch_size: 100
security:
    jwt:
        access-token-validity-ms: 3600000
payment:
    order-ttl: ${PAYMENT_ORDER_TTL}
    success-url: ${PAYMENT_SUCCESS_URL}
    fail-url: ${PAYMENT_FAIL_URL}
    toss:
        base-url: ${TOSS_BASE_URL}
        client-key: ${TOSS_CLIENT_KEY}
        secret-key: ${TOSS_SECRET_KEY}
management: 
    endpoints: # 입구 개방(prometheus)
        web:
            exposure: # /actuator/{include}
                include: health, info, prometheus
    tracing: # 추적 설정
        sampling:
            probability: 1.0
        propagation:
            type: w3c
    otlp:
        tracing: # 데이터 내보내기(OTEL)
            endpoint: ${OTLP_ENDPOINT}
            transport: http
    metrics:
        distribution:
            percentiles-histogram:
                http.server.requests: true
        tags:
            application: ${spring.application.name}

logging:
    pattern:
        console: "%5p [%t] [%X{traceId:-},%X{spanId:-}] %c{1} - %m%n"
    level:
        root: INFO
        com.solo.ptmatch: DEBUG
        org.springframework.web.servlet.DispatcherServlet: DEBUG
        net.ttddyy.observation: INFO
