spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

security:
    jwt:
        secret: ${SPRING_JWT_SECRET}

minio:
    endpoint: ${MINIO_ENDPOINT}
    bucket: ${MINIO_BUCKET}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    presign-expiry: ${MINIO_PRESIGN_EXPIRY}
    public-url: ${MINIO_PUBLIC_URL}
